### ISSUE TITLE
Duplicate pages still occurring

### ISSUE THREAD

**Issue by alveerak** [FBU-a3/convo#29]
I thought I fixed the duplicate page problem but actually, I just improved it. There is still some bug that causes a few pages to duplicate. Turns out the parse query for adding all the pages into a hashmap only returns an array of size 100 (perhaps this is the number of unique pages, because with duplicates there are currently 184 pages in parse page class). Then, the hashmap is only of size 69. It doesn't include all the pages. I don't know why this is occurring though.

**Comment by alex-goodman** [comment]
FIXED
